DROP TABLE IF EXISTS yhteisosivu CASCADE;
DROP TABLE IF EXISTS jasenet CASCADE;
DROP TABLE IF EXISTS yksprofiili CASCADE;
DROP TABLE IF EXISTS profiili CASCADE;
DROP TABLE IF EXISTS viesti CASCADE;
DROP TABLE IF EXISTS kayttaja CASCADE;